### ISSUE TITLE
Volume Editing does not work

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/HP3ParPlugin#2]
Editing a volume in the current implementation does not work:
```
2016-04-24 18:02:23,259 [pool-1-thread-38] INFO  doFormSubmit(APIProvider.java:1259) - FORM SUBMIT com.cisco.matday.ucsd.hp3par.reports.actions.EditVolumeActionForm
2016-04-24 18:02:23,296 [pool-1-thread-38] WARN  handlePageValidate(WizardController.java:665) - Error while validating page
java.lang.NullPointerException
	at com.cisco.matday.ucsd.hp3par.account.inventory.HP3ParInventory.getVolumeInfo(HP3ParInventory.java:229)
	at com.cisco.matday.ucsd.hp3par.tasks.volumes.HP3ParVolumeExecute.edit(HP3ParVolumeExecute.java:213)
	at com.cisco.matday.ucsd.hp3par.reports.volume.actions.EditVolumeAction.validatePageData(EditVolumeAction.java:121)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.handlePageValidate(WizardController.java:660)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.handleValidate(WizardController.java:893)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.doFormSubmit(WizardController.java:338)
	at com.cloupia.service.cIM.inframgr.APIProvider.doFormSubmit(APIProvider.java:1273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Looks like the way it's pulling the information from the persistent store is broken

**Comment by mattsday** [comment]
Fixed in https://github.com/CiscoUKIDCDev/HP3ParPlugin/commit/cea4879db39a9ead33b9b9aa3b63253d32899794
