### ISSUE TITLE
Editing a CPG with null copyCPG fails

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/HP3ParPlugin#34]
```
2016-05-03 21:20:20,559 [pool-1-thread-48] WARN  getCpgInfo(HP3ParInventory.java:292) - CPG not found in cache: null
2016-05-03 21:20:20,559 [pool-1-thread-48] WARN  executeOperation(ServiceProvider.java:757) - Error in operation
java.lang.NullPointerException
	at com.cisco.matday.ucsd.hp3par.reports.volume.actions.EditVolumeAction.loadDataToPage(EditVolumeAction.java:92)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.initializePage(WizardController.java:538)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.getInitialFormData(WizardController.java:456)
	at com.cloupia.service.cIM.inframgr.APIProvider.getInitialFormData(APIProvider.java:1180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattsday** [comment]
Fixed in https://github.com/CiscoUKIDCDev/HP3ParPlugin/commit/4ad062bff242e12959f3c8b25607ad1520e09bdd
