### ISSUE TITLE
CPG volume list drilldown is broken

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/HP3ParPlugin#36]
```
2016-05-04 21:30:40,895 [pool-1-thread-22] WARN  getTabularReport(InfraReportsUtil.java:552) - Error during report generation
java.lang.NullPointerException
	at com.cisco.matday.ucsd.hp3par.reports.cpg.drilldown.CpgVolumeReportImpl.getTabularReportReport(CpgVolumeReportImpl.java:86)
	at com.cloupia.service.cIM.inframgr.InfraReportsUtil.getTabularReport(InfraReportsUtil.java:526)
	at com.cloupia.service.cIM.inframgr.APIProvider.getTabularReport(APIProvider.java:855)
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-05-04 21:30:40,895 [pool-1-thread-22] WARN  executeOperation(ServiceProvider.java:757) - Error in operation
java.lang.NullPointerException
	at com.cisco.matday.ucsd.hp3par.reports.cpg.drilldown.CpgVolumeReportImpl.getTabularReportReport(CpgVolumeReportImpl.java:86)
	at com.cloupia.service.cIM.inframgr.InfraReportsUtil.getTabularReport(InfraReportsUtil.java:526)
	at com.cloupia.service.cIM.inframgr.APIProvider.getTabularReport(APIProvider.java:855)
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattsday** [comment]
This should be fixed in https://github.com/CiscoUKIDCDev/HP3ParPlugin/commit/56de36bfda9de7a36ef6fbf7bf2ff81558f129f8 as the copy CPG cannot be null
