### ISSUE TITLE
Editing a volume without a copy CPG fails

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/HP3ParPlugin#50]
The ```snapCPG``` value is being passed with the REST call even if it's blank - API docs say this is ignored, but should test before sending the request if == "" and set to null

```
2016-05-23 23:03:11,130 [pool-1-thread-24] INFO  doFormSubmit(APIProvider.java:1259) - FORM SUBMIT com.cisco.matday.ucsd.hp3par.reports.actions.EditVolumeActionForm
2016-05-23 23:03:11,165 [pool-1-thread-24] INFO  edit(HP3ParVolumeExecute.java:245) - Vol REST Lookup: SSD_r1
2016-05-23 23:03:11,165 [pool-1-thread-24] INFO  edit(HP3ParVolumeExecute.java:246) - Copy CPG Name:
2016-05-23 23:03:11,165 [pool-1-thread-24] INFO  edit(HP3ParVolumeExecute.java:266) - HP 3PAR Edit REST: {"newName":"abcdefghi","comment":"No commen","snapCPG":""}
2016-05-23 23:03:11,603 [pool-1-thread-24] WARN  validatePageData(EditVolumeAction.java:138) - Failed to edit volume: Error code: 45: invalid input: empty string
2016-05-23 23:03:11,604 [pool-1-thread-24] WARN  handlePageValidate(WizardController.java:665) - Error while validating page
com.cisco.matday.ucsd.hp3par.exceptions.HP3ParVolumeException: Failed to edit volume: Error code: 45: invalid input: empty string
	at com.cisco.matday.ucsd.hp3par.reports.volume.actions.EditVolumeAction.validatePageData(EditVolumeAction.java:139)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.handlePageValidate(WizardController.java:660)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.handleValidate(WizardController.java:893)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.doFormSubmit(WizardController.java:338)
	at com.cloupia.service.cIM.inframgr.APIProvider.doFormSubmit(APIProvider.java:1273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattsday** [comment]
Nope, wasn't fixed in https://github.com/CiscoUKIDCDev/HP3ParPlugin/commit/c3c3ddfe6b59b9616372643e1a239a4692a6fefa

**Comment by mattsday** [comment]
No it was fixed - test didn't upload the code :)
