### ISSUE TITLE
FCWWN and iSCSI remove under Paths doesn't populate based on context

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/HP3ParPlugin#52]

**Comment by mattsday** [comment]
```2016-06-03 20:52:39,603 [pool-1-thread-31] INFO  getInitialFormData(APIProvider.java:1169) - FORM INIT com.cisco.matday.ucsd.hp3par.reports.hosts.actions.RemoveFCActionfalsetrue
2016-06-03 20:52:39,626 [pool-1-thread-31] INFO  getInitialFormData(WizardController.java:470) - getInitial form data com.cisco.matday.ucsd.hp3par.reports.hosts.actions.RemoveFCActionfalsetrue
2016-06-03 20:52:39,753 [pool-1-thread-32] WARN  getTabularReportReport(HP3ParFCSelector.java:78) - Context: 3PAR;10@3PAR@renamedNewHost
2016-06-03 20:52:39,776 [pool-1-thread-32] WARN  getHostInfo(HP3ParInventory.java:359) - Host not found in cache: 10
2016-06-03 20:52:39,776 [pool-1-thread-32] WARN  getTabularReport(InfraReportsUtil.java:552) - Error during report generation
java.lang.NullPointerException
	at com.cisco.matday.ucsd.hp3par.inputs.HP3ParFCSelector.generateForSpecificHost(HP3ParFCSelector.java:97)
	at com.cisco.matday.ucsd.hp3par.inputs.HP3ParFCSelector.getTabularReportReport(HP3ParFCSelector.java:82)
	at com.cloupia.service.cIM.inframgr.InfraReportsUtil.getTabularReport(InfraReportsUtil.java:526)
	at com.cloupia.service.cIM.inframgr.APIProvider.getTabularReport(APIProvider.java:855)
	at com.cloupia.service.cIM.inframgr.APIProvider.getFormTabularReport(APIProvider.java:1327)
	at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-06-03 20:52:39,777 [pool-1-thread-32] WARN  executeOperation(ServiceProvider.java:757) - Error in operation```

**Comment by mattsday** [comment]
Don't regress host drilldown action in fix
