### ISSUE TITLE
Editing host sets is broken

### ISSUE THREAD

**Issue by mattsday** [CiscoUKIDCDev/HP3ParPlugin#7]
```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
	at com.cisco.matday.ucsd.hp3par.tasks.hostsets.HP3ParHostSetExecute.edit(HP3ParHostSetExecute.java:156)
	at com.cisco.matday.ucsd.hp3par.reports.hostsets.actions.EditHostSetAction.validatePageData(EditHostSetAction.java:114)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.handlePageValidate(WizardController.java:660)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.handleValidate(WizardController.java:893)
	at com.cloupia.service.cIM.inframgr.forms.wizard.WizardController.doFormSubmit(WizardController.java:338)
	at com.cloupia.service.cIM.inframgr.APIProvider.doFormSubmit(APIProvider.java:1273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.cloupia.fw.services.provider.ServiceProvider.executeOperation(ServiceProvider.java:752)
	at com.cloupia.fw.services.provider.OperationRequestProcessor.run(OperationRequestProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattsday** [comment]
Fixed in https://github.com/CiscoUKIDCDev/HP3ParPlugin/commit/a1ca59ce5d137acd3f4c78caea1e9d35ce5d4e1c
